// app/components/Footer.tsx
import Link from 'next/link'
import './footer.scss'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTwitter, faLinkedin, faGithub, faFacebook } from "@fortawesome/free-brands-svg-icons";
import { faCode } from '@fortawesome/free-solid-svg-icons';


export const Footer = () => {
  return (
    <footer>
        <Link href="/" className="copyright">&copy; Wuletaw Wonte</Link>
        <div className="social">
            <Link href="https://twitter.com/wuletaww" target='_blank'>
                <FontAwesomeIcon icon={faTwitter} size='xl' style={{ color: "rgb(133, 191, 247)" }} />
            </Link>
            <Link href="https://www.linkedin.com/in/wuletaw-wonte" target='_blank'>
                <FontAwesomeIcon icon={faLinkedin} size='xl' style={{ color: "rgb(41, 102, 188)" }} />
            </Link>
            <Link href="https://github.com/wuletawwonte/" target='_blank'>
                <FontAwesomeIcon icon={faGithub} size='xl' style={{ color: "white" }} />
            </Link>
            <Link href="https://www.facebook.com/wuletawbeza" target='_blank'>
                <FontAwesomeIcon icon={faFacebook} size='xl' style={{ color: "#1877F2" }} />
            </Link>
        </div>
        <div className="source">        
            <Link href="https://github.com/wuletawwonte/wuletawwonte.com.git" className='source__link' target='_blank'>
                <FontAwesomeIcon icon={faCode} size='lg' />
            </Link>
        </div>
    </footer>
  )
}

// components/Footer.vue
<template>
  <footer class="py-4">
    <div class="flex justify-center">
      <a
        href="https://www.linkedin.com/in/wuletawwonte/"
        class="text-lg text-base-content opacity-50 hover:opacity-100"
        title="LinkedIn"
        target="_blank"
      >
        <icon name="fa-brands:linkedin" class="h-8 w-8" />
      </a>
      <a
        href="https://github.com/wuletawwonte/"
        class="ml-4 text-lg text-base-content opacity-50 hover:opacity-100"
        title="GitHub"
        target="_blank"
      >
        <icon name="fa-brands:github" class="h-8 w-8" />
      </a>
      <a
        href="https://twitter.com/wuletawwonte"
        class="ml-4 text-lg text-base-content opacity-50 hover:opacity-100"
        title="Twitter"
        target="_blank"
      >
        <icon name="fa6-brands:x-twitter" class="h-8 w-8" />
      </a>
    </div>
    <p class="mt-4 text-center text-base-content">
      &copy; {{ new Date().getFullYear() }} Wuletaw Wonte. All rights reserved.
    </p>
  </footer>
</template>
